name: Deploy A Service to EB

on:
  workflow_dispatch:
  push:
    paths:
      - 'a-service/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build JAR
        working-directory: a-service
        run: ./gradlew clean build

      - name: Create ZIP for EB
        run: |
          cp a-service/Dockerfile .
          cp a-service/build/libs/*.jar app.jar
          cp a-service/src/main/resources/application-eb.properties application.properties
          zip a-service.zip Dockerfile app.jar application.properties

      - name: List contents of a-service.zip
        run: unzip -l a-service.zip

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          # GitHub Repository > Settings > Secrets > Actions 에서 AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY 등록
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: a-service-app
          environment_name: a-service-app-eb
          version_label: a-${{ github.sha }}
          region: ap-northeast-2
          deployment_package: a-service.zip
