name: Deploy B Service to EB

on:
  workflow_dispatch:
  push:
    paths:
      - 'b-service/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build JAR
        working-directory: b-service
        run: ./gradlew clean build

      - name: Create ZIP for EB
        run: |
          mkdir bundle
          cp b-service/Dockerfile bundle/
          cp b-service/build/libs/*.jar bundle/app.jar
          cp b-service/src/main/resources/application-eb.properties bundle/application.properties
          zip -r b-service.zip bundle/

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: b-service-app
          environment_name: b-service-eb
          version_label: b-${{ github.sha }}
          region: ap-northeast-2
          deployment_package: b-service.zip
